version: "2"
services:
  jenkins-master-service:
    image: ubuntucore/snappy-jenkins-master
    ports:
      - 8080:8080
    restart: always
    user: root
    environment:
      - "constraint:public==yes"

  snappy-proxy:
    depends_on:
      - jenkins-master-service
    image: ubuntucore/snappy-jenkins-proxy
    ports:
      - 8081:80
    restart: always
    environment:
      - "constraint:public==yes"

  snapversion:
    image: ubuntucore/snapversion
    ports:
      - 8000:8000
    restart: always

  jenkins-slave-vivid:
    image: ubuntucore/snappy-jenkins-slave-vivid
    command: -username admin -password snappy -executors 2 -name jenkins-slave-vivid-1 -labels vivid -master http://jenkins-master-service:8080
    privileged: true
    restart: always
    user: jenkins-slave

  jenkins-slave-xenial:
    extends: jenkins-slave-vivid
    image: ubuntucore/snappy-jenkins-slave-xenial
    command: -username admin -password snappy -executors 2 -name jenkins-slave-xenial-1 -labels xenial -master http://jenkins-master-service:8080

  hubot:
    image: fgimenez/hubot
    ports:
      - 9090:9090
    restart: always
    environment:
      - TELEGRAM_TOKEN
      - HUBOT_LOG_LEVEL
      - HUBOT_JENKINS_URL
      - HUBOT_JENKINS_AUTH
      - "constraint:public==yes"
